---
# Configs for confluence-server
- name: Configure confluence-application.properties
  template:
   src: confluence-init.properties.j2
   dest: /opt/atlassian/confluence/confluence/WEB-INF/classes/confluence-init.properties
   owner: confluence
   group: confluence
   mode: 0644
   backup: yes
  notify: restart confluence
 
 
- name: Configure setenv.sh
  template:
   src: setenv.sh.j2
   dest: /opt/atlassian/confluence/bin/setenv.sh
   owner: confluence
   group: confluence
   mode: 0755
   backup: yes
  notify: restart confluence
  tags: configs
 
- name: Create confluence service file
  copy:
   src: confluence.service
   dest: /etc/systemd/system
 
- name: Enable confluence service
  service:
   name: confluence.service
   enabled: yes
   state: started
 

